-- SELECT *
-- FROM noaa.`stormdata`
-- LIMIT 15;
-- order by EVENT_TYPE asc; 
-- alter table noaa.`stormdata`
-- order by EVENT_TYPE asc;

-- LIMIT 15;
-- WHERE BEGIN_LAT = '0';
-- DELETE FROM noaa.`stormdata`;
-- LIMIT 10;
-- WHERE BEGIN_YEARMONTH='BEGIN_YEARMONTH';
-- UPDATE noaa.`stormdata` 
-- SET END_LON = 0
-- WHERE END_LAT = '';
-- where EVENT_ID = 238280;
-- BEGIN_LON = '' or BEGIN_LAT = '';
-- where BEGIN_LON != 0;
-- SELECT BEGIN_LAT 
-- from noaa.`storm Table`
-- where BEGIN_LAT = 0;
-- DELETE FROM noaa.`1950_2004 - copy` where BEGIN_YEARMONTH = 195004;
-- DELETE FROM noaa.`storm Table`;
-- ALTER TABLE noaa.`storm table`
-- MODIFY COLUMN DAMAGE_PROPERTY int;
--  where BEGIN_YEARMONTH = 195004;
-- show variables like "secure_file_priv";
-- SHOW GLOBAL variables like 'local_infile';
-- set global local_infile = ON;
-- Load data local infile `'secure_file_priv', 'C:\\ProgramData\\MySQL\\MySQL Server 8.0\\Uploads\\'
-- ` into table noaa.stormdata
-- SET GLOBAL innodb_buffer_pool_size=268435456;
-- show global variables like 'innodb_buffer_pool_size';

Load data local infile 'C:\\ProgramData\\MySQL\\MySQL Server 8.0\\Uploads\\2011-2021.csv'
into table noaa.`stormdata`
fields terminated by ',' 
-- enclosed by '"' 
lines terminated by '\n'
ignore 1 rows;

-- CREATE TABLE `noaa`.`stormdata2` (
-- `EPISODE_ID` INT NOT NULL,
-- `EVENT_ID` INT NULL,
-- `BEGIN_YEARMONTH` INT NULL,
-- `END_YEARMONTH` INT NULL,
-- `STATE` TEXT NULL,
-- `STATE_FIPS` INT NULL,
-- `EVENT_TYPE` TEXT NULL,
-- `INJURIES_DIRECT` INT NULL,
-- `INJURIES_INDIRECT` INT NULL,
-- `DEATHS_DIRECT` INT NULL,
-- `DEATHS_INDIRECT` INT NULL,
-- `DAMAGED_PROPERTY` BIGINT NULL,
-- `DAMAGED_CROPS` BIGINT NULL,
-- `BEGIN_LAT` TEXT NULL,
-- `BEGIN_LON` TEXT NULL,
-- `END_LAT` TEXT NULL,
-- `END_LON` TEXT NULL,
--   PRIMARY KEY (`EPISODE_ID`))
-- ENGINE = InnoDB
-- DEFAULT CHARACTER SET = utf8mb4;
-- -- Load data local infile 'C:\\ProgramData\\MySQL\\MySQL Server 8.0\\Uploads\\FINAL DATA (1950-2021) Copy.xlsx'
-- -- into table noaa.`stormdata`
-- -- fields terminated by ',' 
-- -- enclosed by '"' 
-- -- lines terminated by '\n' 
-- -- ignore 1 rows;
-- SELECT count(*) from `noaa`.`puerto rico data`;
-- SELECT DISTINCT count(*) from `noaa`.`stormdata` GROUP BY STATE; 

-- SELECT *
-- FROM `noaa`.stormdata
-- where EPISODE_ID = 241781;

CREATE TABLE `noaa`.`OHIO DATA SUMMARY`
AS SELECT EVENT_ID, sum(INJURIES_DIRECT) AS sum_injuries_direct, sum(INJURIES_INDIRECT) AS sum_injuries_indirect, sum(DAMAGED_PROPERTY) AS sum_damaged_property, sum(DAMAGED_CROPS) AS sum_damaged_crops
FROM noaa.`OHIO DATA`
GROUP BY EVENT_ID;
SELECT *
FROM `noaa`.`ohio data summary`
WHERE EVENT_ID = 53835;

-- CREATE TABLE noaa.`ALABAMA DATA` AS SELECT EPISODE_ID, EVENT_ID, BEGIN_YEARMONTH, END_YEARMONTH, STATE, STATE_FIPS, EVENT_TYPE, INJURIES_DIRECT, INJURIES_INDIRECT, DEATHS_DIRECT, DEATHS_INDIRECT, DAMAGED_PROPERTY, DAMAGED_CROPS, BEGIN_LAT, BEGIN_LON, END_LAT, END_LON FROM noaa.`stormdata` WHERE STATE_FIPS= '1';
-- CREATE TABLE noaa.`ALASKA DATA` AS SELECT EPISODE_ID, EVENT_ID, BEGIN_YEARMONTH, END_YEARMONTH, STATE, STATE_FIPS, EVENT_TYPE, INJURIES_DIRECT, INJURIES_INDIRECT, DEATHS_DIRECT, DEATHS_INDIRECT, DAMAGED_PROPERTY, DAMAGED_CROPS, BEGIN_LAT, BEGIN_LON, END_LAT, END_LON FROM noaa.`stormdata` WHERE STATE_FIPS= '2';
-- CREATE TABLE noaa.`ARIZONA DATA` AS SELECT EPISODE_ID, EVENT_ID, BEGIN_YEARMONTH, END_YEARMONTH, STATE, STATE_FIPS, EVENT_TYPE, INJURIES_DIRECT, INJURIES_INDIRECT, DEATHS_DIRECT, DEATHS_INDIRECT, DAMAGED_PROPERTY, DAMAGED_CROPS, BEGIN_LAT, BEGIN_LON, END_LAT, END_LON FROM noaa.`stormdata` WHERE STATE_FIPS= '4';
-- CREATE TABLE noaa.`ARKANSAS DATA` AS SELECT EPISODE_ID, EVENT_ID, BEGIN_YEARMONTH, END_YEARMONTH, STATE, STATE_FIPS, EVENT_TYPE, INJURIES_DIRECT, INJURIES_INDIRECT, DEATHS_DIRECT, DEATHS_INDIRECT, DAMAGED_PROPERTY, DAMAGED_CROPS, BEGIN_LAT, BEGIN_LON, END_LAT, END_LON FROM noaa.`stormdata` WHERE STATE_FIPS= '5';
-- CREATE TABLE noaa.`CALIFORNIA DATA` AS SELECT EPISODE_ID, EVENT_ID, BEGIN_YEARMONTH, END_YEARMONTH, STATE, STATE_FIPS, EVENT_TYPE, INJURIES_DIRECT, INJURIES_INDIRECT, DEATHS_DIRECT, DEATHS_INDIRECT, DAMAGED_PROPERTY, DAMAGED_CROPS, BEGIN_LAT, BEGIN_LON, END_LAT, END_LON FROM noaa.`stormdata` WHERE STATE_FIPS= '6';
-- CREATE TABLE noaa.`COLORADO DATA` AS SELECT EPISODE_ID, EVENT_ID, BEGIN_YEARMONTH, END_YEARMONTH, STATE, STATE_FIPS, EVENT_TYPE, INJURIES_DIRECT, INJURIES_INDIRECT, DEATHS_DIRECT, DEATHS_INDIRECT, DAMAGED_PROPERTY, DAMAGED_CROPS, BEGIN_LAT, BEGIN_LON, END_LAT, END_LON FROM noaa.`stormdata` WHERE STATE_FIPS= '8';
-- CREATE TABLE noaa.`CONNECTICUT DATA` AS SELECT EPISODE_ID, EVENT_ID, BEGIN_YEARMONTH, END_YEARMONTH, STATE, STATE_FIPS, EVENT_TYPE, INJURIES_DIRECT, INJURIES_INDIRECT, DEATHS_DIRECT, DEATHS_INDIRECT, DAMAGED_PROPERTY, DAMAGED_CROPS, BEGIN_LAT, BEGIN_LON, END_LAT, END_LON FROM noaa.`stormdata` WHERE STATE_FIPS= '9';
-- CREATE TABLE noaa.`DELAWARE DATA` AS SELECT EPISODE_ID, EVENT_ID, BEGIN_YEARMONTH, END_YEARMONTH, STATE, STATE_FIPS, EVENT_TYPE, INJURIES_DIRECT, INJURIES_INDIRECT, DEATHS_DIRECT, DEATHS_INDIRECT, DAMAGED_PROPERTY, DAMAGED_CROPS, BEGIN_LAT, BEGIN_LON, END_LAT, END_LON FROM noaa.`stormdata` WHERE STATE_FIPS= '10';
-- CREATE TABLE noaa.`DISTRICT OF COLUMBIA DATA` AS SELECT EPISODE_ID, EVENT_ID, BEGIN_YEARMONTH, END_YEARMONTH, STATE, STATE_FIPS, EVENT_TYPE, INJURIES_DIRECT, INJURIES_INDIRECT, DEATHS_DIRECT, DEATHS_INDIRECT, DAMAGED_PROPERTY, DAMAGED_CROPS, BEGIN_LAT, BEGIN_LON, END_LAT, END_LON FROM noaa.`stormdata` WHERE STATE_FIPS= '11';
-- CREATE TABLE noaa.`FLORIDA DATA` AS SELECT EPISODE_ID, EVENT_ID, BEGIN_YEARMONTH, END_YEARMONTH, STATE, STATE_FIPS, EVENT_TYPE, INJURIES_DIRECT, INJURIES_INDIRECT, DEATHS_DIRECT, DEATHS_INDIRECT, DAMAGED_PROPERTY, DAMAGED_CROPS, BEGIN_LAT, BEGIN_LON, END_LAT, END_LON FROM noaa.`stormdata` WHERE STATE_FIPS= '12';
-- CREATE TABLE noaa.`GEORGIA DATA` AS SELECT EPISODE_ID, EVENT_ID, BEGIN_YEARMONTH, END_YEARMONTH, STATE, STATE_FIPS, EVENT_TYPE, INJURIES_DIRECT, INJURIES_INDIRECT, DEATHS_DIRECT, DEATHS_INDIRECT, DAMAGED_PROPERTY, DAMAGED_CROPS, BEGIN_LAT, BEGIN_LON, END_LAT, END_LON FROM noaa.`stormdata` WHERE STATE_FIPS= '13';
-- CREATE TABLE noaa.`HAWAII DATA` AS SELECT EPISODE_ID, EVENT_ID, BEGIN_YEARMONTH, END_YEARMONTH, STATE, STATE_FIPS, EVENT_TYPE, INJURIES_DIRECT, INJURIES_INDIRECT, DEATHS_DIRECT, DEATHS_INDIRECT, DAMAGED_PROPERTY, DAMAGED_CROPS, BEGIN_LAT, BEGIN_LON, END_LAT, END_LON FROM noaa.`stormdata` WHERE STATE_FIPS= '15';
-- CREATE TABLE noaa.`IDAHO DATA` AS SELECT EPISODE_ID, EVENT_ID, BEGIN_YEARMONTH, END_YEARMONTH, STATE, STATE_FIPS, EVENT_TYPE, INJURIES_DIRECT, INJURIES_INDIRECT, DEATHS_DIRECT, DEATHS_INDIRECT, DAMAGED_PROPERTY, DAMAGED_CROPS, BEGIN_LAT, BEGIN_LON, END_LAT, END_LON FROM noaa.`stormdata` WHERE STATE_FIPS= '16';
-- CREATE TABLE noaa.`ILLINOIS DATA` AS SELECT EPISODE_ID, EVENT_ID, BEGIN_YEARMONTH, END_YEARMONTH, STATE, STATE_FIPS, EVENT_TYPE, INJURIES_DIRECT, INJURIES_INDIRECT, DEATHS_DIRECT, DEATHS_INDIRECT, DAMAGED_PROPERTY, DAMAGED_CROPS, BEGIN_LAT, BEGIN_LON, END_LAT, END_LON FROM noaa.`stormdata` WHERE STATE_FIPS= '17';
-- CREATE TABLE noaa.`INDIANA DATA` AS SELECT EPISODE_ID, EVENT_ID, BEGIN_YEARMONTH, END_YEARMONTH, STATE, STATE_FIPS, EVENT_TYPE, INJURIES_DIRECT, INJURIES_INDIRECT, DEATHS_DIRECT, DEATHS_INDIRECT, DAMAGED_PROPERTY, DAMAGED_CROPS, BEGIN_LAT, BEGIN_LON, END_LAT, END_LON FROM noaa.`stormdata` WHERE STATE_FIPS= '18';
-- CREATE TABLE noaa.`IOWA DATA` AS SELECT EPISODE_ID, EVENT_ID, BEGIN_YEARMONTH, END_YEARMONTH, STATE, STATE_FIPS, EVENT_TYPE, INJURIES_DIRECT, INJURIES_INDIRECT, DEATHS_DIRECT, DEATHS_INDIRECT, DAMAGED_PROPERTY, DAMAGED_CROPS, BEGIN_LAT, BEGIN_LON, END_LAT, END_LON FROM noaa.`stormdata` WHERE STATE_FIPS= '19';
-- CREATE TABLE noaa.`KANSAS DATA` AS SELECT EPISODE_ID, EVENT_ID, BEGIN_YEARMONTH, END_YEARMONTH, STATE, STATE_FIPS, EVENT_TYPE, INJURIES_DIRECT, INJURIES_INDIRECT, DEATHS_DIRECT, DEATHS_INDIRECT, DAMAGED_PROPERTY, DAMAGED_CROPS, BEGIN_LAT, BEGIN_LON, END_LAT, END_LON FROM noaa.`stormdata` WHERE STATE_FIPS= '20';
-- CREATE TABLE noaa.`KENTUCKY DATA` AS SELECT EPISODE_ID, EVENT_ID, BEGIN_YEARMONTH, END_YEARMONTH, STATE, STATE_FIPS, EVENT_TYPE, INJURIES_DIRECT, INJURIES_INDIRECT, DEATHS_DIRECT, DEATHS_INDIRECT, DAMAGED_PROPERTY, DAMAGED_CROPS, BEGIN_LAT, BEGIN_LON, END_LAT, END_LON FROM noaa.`stormdata` WHERE STATE_FIPS= '21';
-- CREATE TABLE noaa.`LOUISIANA DATA` AS SELECT EPISODE_ID, EVENT_ID, BEGIN_YEARMONTH, END_YEARMONTH, STATE, STATE_FIPS, EVENT_TYPE, INJURIES_DIRECT, INJURIES_INDIRECT, DEATHS_DIRECT, DEATHS_INDIRECT, DAMAGED_PROPERTY, DAMAGED_CROPS, BEGIN_LAT, BEGIN_LON, END_LAT, END_LON FROM noaa.`stormdata` WHERE STATE_FIPS= '22';
-- CREATE TABLE noaa.`MAINE DATA` AS SELECT EPISODE_ID, EVENT_ID, BEGIN_YEARMONTH, END_YEARMONTH, STATE, STATE_FIPS, EVENT_TYPE, INJURIES_DIRECT, INJURIES_INDIRECT, DEATHS_DIRECT, DEATHS_INDIRECT, DAMAGED_PROPERTY, DAMAGED_CROPS, BEGIN_LAT, BEGIN_LON, END_LAT, END_LON FROM noaa.`stormdata` WHERE STATE_FIPS= '23';
-- CREATE TABLE noaa.`MARYLAND DATA` AS SELECT EPISODE_ID, EVENT_ID, BEGIN_YEARMONTH, END_YEARMONTH, STATE, STATE_FIPS, EVENT_TYPE, INJURIES_DIRECT, INJURIES_INDIRECT, DEATHS_DIRECT, DEATHS_INDIRECT, DAMAGED_PROPERTY, DAMAGED_CROPS, BEGIN_LAT, BEGIN_LON, END_LAT, END_LON FROM noaa.`stormdata` WHERE STATE_FIPS= '24';
-- CREATE TABLE noaa.`MASSACHUSETTS DATA` AS SELECT EPISODE_ID, EVENT_ID, BEGIN_YEARMONTH, END_YEARMONTH, STATE, STATE_FIPS, EVENT_TYPE, INJURIES_DIRECT, INJURIES_INDIRECT, DEATHS_DIRECT, DEATHS_INDIRECT, DAMAGED_PROPERTY, DAMAGED_CROPS, BEGIN_LAT, BEGIN_LON, END_LAT, END_LON FROM noaa.`stormdata` WHERE STATE_FIPS= '25';
-- CREATE TABLE noaa.`MICHIGAN DATA` AS SELECT EPISODE_ID, EVENT_ID, BEGIN_YEARMONTH, END_YEARMONTH, STATE, STATE_FIPS, EVENT_TYPE, INJURIES_DIRECT, INJURIES_INDIRECT, DEATHS_DIRECT, DEATHS_INDIRECT, DAMAGED_PROPERTY, DAMAGED_CROPS, BEGIN_LAT, BEGIN_LON, END_LAT, END_LON FROM noaa.`stormdata` WHERE STATE_FIPS= '26';
-- CREATE TABLE noaa.`MINNESOTA DATA` AS SELECT EPISODE_ID, EVENT_ID, BEGIN_YEARMONTH, END_YEARMONTH, STATE, STATE_FIPS, EVENT_TYPE, INJURIES_DIRECT, INJURIES_INDIRECT, DEATHS_DIRECT, DEATHS_INDIRECT, DAMAGED_PROPERTY, DAMAGED_CROPS, BEGIN_LAT, BEGIN_LON, END_LAT, END_LON FROM noaa.`stormdata` WHERE STATE_FIPS= '27';
-- CREATE TABLE noaa.`MISSISSIPPI DATA` AS SELECT EPISODE_ID, EVENT_ID, BEGIN_YEARMONTH, END_YEARMONTH, STATE, STATE_FIPS, EVENT_TYPE, INJURIES_DIRECT, INJURIES_INDIRECT, DEATHS_DIRECT, DEATHS_INDIRECT, DAMAGED_PROPERTY, DAMAGED_CROPS, BEGIN_LAT, BEGIN_LON, END_LAT, END_LON FROM noaa.`stormdata` WHERE STATE_FIPS= '28';
-- CREATE TABLE noaa.`MISSOURI DATA` AS SELECT EPISODE_ID, EVENT_ID, BEGIN_YEARMONTH, END_YEARMONTH, STATE, STATE_FIPS, EVENT_TYPE, INJURIES_DIRECT, INJURIES_INDIRECT, DEATHS_DIRECT, DEATHS_INDIRECT, DAMAGED_PROPERTY, DAMAGED_CROPS, BEGIN_LAT, BEGIN_LON, END_LAT, END_LON FROM noaa.`stormdata` WHERE STATE_FIPS= '29';
-- CREATE TABLE noaa.`MONTANA DATA` AS SELECT EPISODE_ID, EVENT_ID, BEGIN_YEARMONTH, END_YEARMONTH, STATE, STATE_FIPS, EVENT_TYPE, INJURIES_DIRECT, INJURIES_INDIRECT, DEATHS_DIRECT, DEATHS_INDIRECT, DAMAGED_PROPERTY, DAMAGED_CROPS, BEGIN_LAT, BEGIN_LON, END_LAT, END_LON FROM noaa.`stormdata` WHERE STATE_FIPS= '30';
-- CREATE TABLE noaa.`NEBRASKA DATA` AS SELECT EPISODE_ID, EVENT_ID, BEGIN_YEARMONTH, END_YEARMONTH, STATE, STATE_FIPS, EVENT_TYPE, INJURIES_DIRECT, INJURIES_INDIRECT, DEATHS_DIRECT, DEATHS_INDIRECT, DAMAGED_PROPERTY, DAMAGED_CROPS, BEGIN_LAT, BEGIN_LON, END_LAT, END_LON FROM noaa.`stormdata` WHERE STATE_FIPS= '31';
-- CREATE TABLE noaa.`NEVADA DATA` AS SELECT EPISODE_ID, EVENT_ID, BEGIN_YEARMONTH, END_YEARMONTH, STATE, STATE_FIPS, EVENT_TYPE, INJURIES_DIRECT, INJURIES_INDIRECT, DEATHS_DIRECT, DEATHS_INDIRECT, DAMAGED_PROPERTY, DAMAGED_CROPS, BEGIN_LAT, BEGIN_LON, END_LAT, END_LON FROM noaa.`stormdata` WHERE STATE_FIPS= '32';
-- CREATE TABLE noaa.`NEW HAMPSHIRE DATA` AS SELECT EPISODE_ID, EVENT_ID, BEGIN_YEARMONTH, END_YEARMONTH, STATE, STATE_FIPS, EVENT_TYPE, INJURIES_DIRECT, INJURIES_INDIRECT, DEATHS_DIRECT, DEATHS_INDIRECT, DAMAGED_PROPERTY, DAMAGED_CROPS, BEGIN_LAT, BEGIN_LON, END_LAT, END_LON FROM noaa.`stormdata` WHERE STATE_FIPS= '33';
-- CREATE TABLE noaa.`NEW JERSEY DATA` AS SELECT EPISODE_ID, EVENT_ID, BEGIN_YEARMONTH, END_YEARMONTH, STATE, STATE_FIPS, EVENT_TYPE, INJURIES_DIRECT, INJURIES_INDIRECT, DEATHS_DIRECT, DEATHS_INDIRECT, DAMAGED_PROPERTY, DAMAGED_CROPS, BEGIN_LAT, BEGIN_LON, END_LAT, END_LON FROM noaa.`stormdata` WHERE STATE_FIPS= '34';
-- CREATE TABLE noaa.`NEW MEXICO DATA` AS SELECT EPISODE_ID, EVENT_ID, BEGIN_YEARMONTH, END_YEARMONTH, STATE, STATE_FIPS, EVENT_TYPE, INJURIES_DIRECT, INJURIES_INDIRECT, DEATHS_DIRECT, DEATHS_INDIRECT, DAMAGED_PROPERTY, DAMAGED_CROPS, BEGIN_LAT, BEGIN_LON, END_LAT, END_LON FROM noaa.`stormdata` WHERE STATE_FIPS= '35';
-- CREATE TABLE noaa.`NEW YORK DATA` AS SELECT EPISODE_ID, EVENT_ID, BEGIN_YEARMONTH, END_YEARMONTH, STATE, STATE_FIPS, EVENT_TYPE, INJURIES_DIRECT, INJURIES_INDIRECT, DEATHS_DIRECT, DEATHS_INDIRECT, DAMAGED_PROPERTY, DAMAGED_CROPS, BEGIN_LAT, BEGIN_LON, END_LAT, END_LON FROM noaa.`stormdata` WHERE STATE_FIPS= '36';
-- CREATE TABLE noaa.`NORTH CAROLINA DATA` AS SELECT EPISODE_ID, EVENT_ID, BEGIN_YEARMONTH, END_YEARMONTH, STATE, STATE_FIPS, EVENT_TYPE, INJURIES_DIRECT, INJURIES_INDIRECT, DEATHS_DIRECT, DEATHS_INDIRECT, DAMAGED_PROPERTY, DAMAGED_CROPS, BEGIN_LAT, BEGIN_LON, END_LAT, END_LON FROM noaa.`stormdata` WHERE STATE_FIPS= '37';
-- CREATE TABLE noaa.`NORTH DAKOTA DATA` AS SELECT EPISODE_ID, EVENT_ID, BEGIN_YEARMONTH, END_YEARMONTH, STATE, STATE_FIPS, EVENT_TYPE, INJURIES_DIRECT, INJURIES_INDIRECT, DEATHS_DIRECT, DEATHS_INDIRECT, DAMAGED_PROPERTY, DAMAGED_CROPS, BEGIN_LAT, BEGIN_LON, END_LAT, END_LON FROM noaa.`stormdata` WHERE STATE_FIPS= '38';
-- CREATE TABLE noaa.`OHIO DATA` AS SELECT EPISODE_ID, EVENT_ID, BEGIN_YEARMONTH, END_YEARMONTH, STATE, STATE_FIPS, EVENT_TYPE, INJURIES_DIRECT, INJURIES_INDIRECT, DEATHS_DIRECT, DEATHS_INDIRECT, DAMAGED_PROPERTY, DAMAGED_CROPS, BEGIN_LAT, BEGIN_LON, END_LAT, END_LON FROM noaa.`stormdata` WHERE STATE_FIPS= '39';
-- CREATE TABLE noaa.`OKLAHOMA DATA` AS SELECT EPISODE_ID, EVENT_ID, BEGIN_YEARMONTH, END_YEARMONTH, STATE, STATE_FIPS, EVENT_TYPE, INJURIES_DIRECT, INJURIES_INDIRECT, DEATHS_DIRECT, DEATHS_INDIRECT, DAMAGED_PROPERTY, DAMAGED_CROPS, BEGIN_LAT, BEGIN_LON, END_LAT, END_LON FROM noaa.`stormdata` WHERE STATE_FIPS= '40';
-- CREATE TABLE noaa.`OREGON DATA` AS SELECT EPISODE_ID, EVENT_ID, BEGIN_YEARMONTH, END_YEARMONTH, STATE, STATE_FIPS, EVENT_TYPE, INJURIES_DIRECT, INJURIES_INDIRECT, DEATHS_DIRECT, DEATHS_INDIRECT, DAMAGED_PROPERTY, DAMAGED_CROPS, BEGIN_LAT, BEGIN_LON, END_LAT, END_LON FROM noaa.`stormdata` WHERE STATE_FIPS= '41';
-- CREATE TABLE noaa.`PENNSYLVANIA DATA` AS SELECT EPISODE_ID, EVENT_ID, BEGIN_YEARMONTH, END_YEARMONTH, STATE, STATE_FIPS, EVENT_TYPE, INJURIES_DIRECT, INJURIES_INDIRECT, DEATHS_DIRECT, DEATHS_INDIRECT, DAMAGED_PROPERTY, DAMAGED_CROPS, BEGIN_LAT, BEGIN_LON, END_LAT, END_LON FROM noaa.`stormdata` WHERE STATE_FIPS= '42';
-- CREATE TABLE noaa.`RHODE ISLAND DATA` AS SELECT EPISODE_ID, EVENT_ID, BEGIN_YEARMONTH, END_YEARMONTH, STATE, STATE_FIPS, EVENT_TYPE, INJURIES_DIRECT, INJURIES_INDIRECT, DEATHS_DIRECT, DEATHS_INDIRECT, DAMAGED_PROPERTY, DAMAGED_CROPS, BEGIN_LAT, BEGIN_LON, END_LAT, END_LON FROM noaa.`stormdata` WHERE STATE_FIPS= '44';
-- CREATE TABLE noaa.`SOUTH CAROLINA DATA` AS SELECT EPISODE_ID, EVENT_ID, BEGIN_YEARMONTH, END_YEARMONTH, STATE, STATE_FIPS, EVENT_TYPE, INJURIES_DIRECT, INJURIES_INDIRECT, DEATHS_DIRECT, DEATHS_INDIRECT, DAMAGED_PROPERTY, DAMAGED_CROPS, BEGIN_LAT, BEGIN_LON, END_LAT, END_LON FROM noaa.`stormdata` WHERE STATE_FIPS= '45';
-- CREATE TABLE noaa.`SOUTH DAKOTA DATA` AS SELECT EPISODE_ID, EVENT_ID, BEGIN_YEARMONTH, END_YEARMONTH, STATE, STATE_FIPS, EVENT_TYPE, INJURIES_DIRECT, INJURIES_INDIRECT, DEATHS_DIRECT, DEATHS_INDIRECT, DAMAGED_PROPERTY, DAMAGED_CROPS, BEGIN_LAT, BEGIN_LON, END_LAT, END_LON FROM noaa.`stormdata` WHERE STATE_FIPS= '46';
-- CREATE TABLE noaa.`TENNESSEE DATA` AS SELECT EPISODE_ID, EVENT_ID, BEGIN_YEARMONTH, END_YEARMONTH, STATE, STATE_FIPS, EVENT_TYPE, INJURIES_DIRECT, INJURIES_INDIRECT, DEATHS_DIRECT, DEATHS_INDIRECT, DAMAGED_PROPERTY, DAMAGED_CROPS, BEGIN_LAT, BEGIN_LON, END_LAT, END_LON FROM noaa.`stormdata` WHERE STATE_FIPS= '47';
-- CREATE TABLE noaa.`TEXAS DATA` AS SELECT EPISODE_ID, EVENT_ID, BEGIN_YEARMONTH, END_YEARMONTH, STATE, STATE_FIPS, EVENT_TYPE, INJURIES_DIRECT, INJURIES_INDIRECT, DEATHS_DIRECT, DEATHS_INDIRECT, DAMAGED_PROPERTY, DAMAGED_CROPS, BEGIN_LAT, BEGIN_LON, END_LAT, END_LON FROM noaa.`stormdata` WHERE STATE_FIPS= '48';
-- CREATE TABLE noaa.`UTAH DATA` AS SELECT EPISODE_ID, EVENT_ID, BEGIN_YEARMONTH, END_YEARMONTH, STATE, STATE_FIPS, EVENT_TYPE, INJURIES_DIRECT, INJURIES_INDIRECT, DEATHS_DIRECT, DEATHS_INDIRECT, DAMAGED_PROPERTY, DAMAGED_CROPS, BEGIN_LAT, BEGIN_LON, END_LAT, END_LON FROM noaa.`stormdata` WHERE STATE_FIPS= '49';
-- CREATE TABLE noaa.`VERMONT DATA` AS SELECT EPISODE_ID, EVENT_ID, BEGIN_YEARMONTH, END_YEARMONTH, STATE, STATE_FIPS, EVENT_TYPE, INJURIES_DIRECT, INJURIES_INDIRECT, DEATHS_DIRECT, DEATHS_INDIRECT, DAMAGED_PROPERTY, DAMAGED_CROPS, BEGIN_LAT, BEGIN_LON, END_LAT, END_LON FROM noaa.`stormdata` WHERE STATE_FIPS= '50';
-- CREATE TABLE noaa.`VIRGINIA DATA` AS SELECT EPISODE_ID, EVENT_ID, BEGIN_YEARMONTH, END_YEARMONTH, STATE, STATE_FIPS, EVENT_TYPE, INJURIES_DIRECT, INJURIES_INDIRECT, DEATHS_DIRECT, DEATHS_INDIRECT, DAMAGED_PROPERTY, DAMAGED_CROPS, BEGIN_LAT, BEGIN_LON, END_LAT, END_LON FROM noaa.`stormdata` WHERE STATE_FIPS= '51';
-- CREATE TABLE noaa.`WASHINGTON DATA` AS SELECT EPISODE_ID, EVENT_ID, BEGIN_YEARMONTH, END_YEARMONTH, STATE, STATE_FIPS, EVENT_TYPE, INJURIES_DIRECT, INJURIES_INDIRECT, DEATHS_DIRECT, DEATHS_INDIRECT, DAMAGED_PROPERTY, DAMAGED_CROPS, BEGIN_LAT, BEGIN_LON, END_LAT, END_LON FROM noaa.`stormdata` WHERE STATE_FIPS= '53';
-- CREATE TABLE noaa.`WEST VIRGINIA DATA` AS SELECT EPISODE_ID, EVENT_ID, BEGIN_YEARMONTH, END_YEARMONTH, STATE, STATE_FIPS, EVENT_TYPE, INJURIES_DIRECT, INJURIES_INDIRECT, DEATHS_DIRECT, DEATHS_INDIRECT, DAMAGED_PROPERTY, DAMAGED_CROPS, BEGIN_LAT, BEGIN_LON, END_LAT, END_LON FROM noaa.`stormdata` WHERE STATE_FIPS= '54';
-- CREATE TABLE noaa.`WISCONSIN DATA` AS SELECT EPISODE_ID, EVENT_ID, BEGIN_YEARMONTH, END_YEARMONTH, STATE, STATE_FIPS, EVENT_TYPE, INJURIES_DIRECT, INJURIES_INDIRECT, DEATHS_DIRECT, DEATHS_INDIRECT, DAMAGED_PROPERTY, DAMAGED_CROPS, BEGIN_LAT, BEGIN_LON, END_LAT, END_LON FROM noaa.`stormdata` WHERE STATE_FIPS= '55';
-- CREATE TABLE noaa.`WYOMING DATA` AS SELECT EPISODE_ID, EVENT_ID, BEGIN_YEARMONTH, END_YEARMONTH, STATE, STATE_FIPS, EVENT_TYPE, INJURIES_DIRECT, INJURIES_INDIRECT, DEATHS_DIRECT, DEATHS_INDIRECT, DAMAGED_PROPERTY, DAMAGED_CROPS, BEGIN_LAT, BEGIN_LON, END_LAT, END_LON FROM noaa.`stormdata` WHERE STATE_FIPS= '56';
-- CREATE TABLE noaa.`LAKE ST CLAIR DATA` AS SELECT EPISODE_ID, EVENT_ID, BEGIN_YEARMONTH, END_YEARMONTH, STATE, STATE_FIPS, EVENT_TYPE, INJURIES_DIRECT, INJURIES_INDIRECT, DEATHS_DIRECT, DEATHS_INDIRECT, DAMAGED_PROPERTY, DAMAGED_CROPS, BEGIN_LAT, BEGIN_LON, END_LAT, END_LON FROM noaa.`stormdata` WHERE STATE_FIPS= '81';
-- CREATE TABLE noaa.`HAWAII WATERS DATA` AS SELECT EPISODE_ID, EVENT_ID, BEGIN_YEARMONTH, END_YEARMONTH, STATE, STATE_FIPS, EVENT_TYPE, INJURIES_DIRECT, INJURIES_INDIRECT, DEATHS_DIRECT, DEATHS_INDIRECT, DAMAGED_PROPERTY, DAMAGED_CROPS, BEGIN_LAT, BEGIN_LON, END_LAT, END_LON FROM noaa.`stormdata` WHERE STATE_FIPS= '84';
-- CREATE TABLE noaa.`GULF OF MEXICO DATA` AS SELECT EPISODE_ID, EVENT_ID, BEGIN_YEARMONTH, END_YEARMONTH, STATE, STATE_FIPS, EVENT_TYPE, INJURIES_DIRECT, INJURIES_INDIRECT, DEATHS_DIRECT, DEATHS_INDIRECT, DAMAGED_PROPERTY, DAMAGED_CROPS, BEGIN_LAT, BEGIN_LON, END_LAT, END_LON FROM noaa.`stormdata` WHERE STATE_FIPS= '85';
-- CREATE TABLE noaa.`E PACIFIC DATA` AS SELECT EPISODE_ID, EVENT_ID, BEGIN_YEARMONTH, END_YEARMONTH, STATE, STATE_FIPS, EVENT_TYPE, INJURIES_DIRECT, INJURIES_INDIRECT, DEATHS_DIRECT, DEATHS_INDIRECT, DAMAGED_PROPERTY, DAMAGED_CROPS, BEGIN_LAT, BEGIN_LON, END_LAT, END_LON FROM noaa.`stormdata` WHERE STATE_FIPS= '86';
-- CREATE TABLE noaa.`ATLANTIC SOUTH DATA` AS SELECT EPISODE_ID, EVENT_ID, BEGIN_YEARMONTH, END_YEARMONTH, STATE, STATE_FIPS, EVENT_TYPE, INJURIES_DIRECT, INJURIES_INDIRECT, DEATHS_DIRECT, DEATHS_INDIRECT, DAMAGED_PROPERTY, DAMAGED_CROPS, BEGIN_LAT, BEGIN_LON, END_LAT, END_LON FROM noaa.`stormdata` WHERE STATE_FIPS= '87';
-- CREATE TABLE noaa.`ATLANTIC NORTH DATA` AS SELECT EPISODE_ID, EVENT_ID, BEGIN_YEARMONTH, END_YEARMONTH, STATE, STATE_FIPS, EVENT_TYPE, INJURIES_DIRECT, INJURIES_INDIRECT, DEATHS_DIRECT, DEATHS_INDIRECT, DAMAGED_PROPERTY, DAMAGED_CROPS, BEGIN_LAT, BEGIN_LON, END_LAT, END_LON FROM noaa.`stormdata` WHERE STATE_FIPS= '88';
-- CREATE TABLE noaa.`GULF OF ALASKA DATA` AS SELECT EPISODE_ID, EVENT_ID, BEGIN_YEARMONTH, END_YEARMONTH, STATE, STATE_FIPS, EVENT_TYPE, INJURIES_DIRECT, INJURIES_INDIRECT, DEATHS_DIRECT, DEATHS_INDIRECT, DAMAGED_PROPERTY, DAMAGED_CROPS, BEGIN_LAT, BEGIN_LON, END_LAT, END_LON FROM noaa.`stormdata` WHERE STATE_FIPS= '89';
-- CREATE TABLE noaa.`LAKE HURON DATA` AS SELECT EPISODE_ID, EVENT_ID, BEGIN_YEARMONTH, END_YEARMONTH, STATE, STATE_FIPS, EVENT_TYPE, INJURIES_DIRECT, INJURIES_INDIRECT, DEATHS_DIRECT, DEATHS_INDIRECT, DAMAGED_PROPERTY, DAMAGED_CROPS, BEGIN_LAT, BEGIN_LON, END_LAT, END_LON FROM noaa.`stormdata` WHERE STATE_FIPS= '90';
-- CREATE TABLE noaa.`LAKE MICHIGAN DATA` AS SELECT EPISODE_ID, EVENT_ID, BEGIN_YEARMONTH, END_YEARMONTH, STATE, STATE_FIPS, EVENT_TYPE, INJURIES_DIRECT, INJURIES_INDIRECT, DEATHS_DIRECT, DEATHS_INDIRECT, DAMAGED_PROPERTY, DAMAGED_CROPS, BEGIN_LAT, BEGIN_LON, END_LAT, END_LON FROM noaa.`stormdata` WHERE STATE_FIPS= '91';
-- CREATE TABLE noaa.`LAKE SUPERIOR DATA` AS SELECT EPISODE_ID, EVENT_ID, BEGIN_YEARMONTH, END_YEARMONTH, STATE, STATE_FIPS, EVENT_TYPE, INJURIES_DIRECT, INJURIES_INDIRECT, DEATHS_DIRECT, DEATHS_INDIRECT, DAMAGED_PROPERTY, DAMAGED_CROPS, BEGIN_LAT, BEGIN_LON, END_LAT, END_LON FROM noaa.`stormdata` WHERE STATE_FIPS= '92';
-- CREATE TABLE noaa.`ST LAWRENCE R DATA` AS SELECT EPISODE_ID, EVENT_ID, BEGIN_YEARMONTH, END_YEARMONTH, STATE, STATE_FIPS, EVENT_TYPE, INJURIES_DIRECT, INJURIES_INDIRECT, DEATHS_DIRECT, DEATHS_INDIRECT, DAMAGED_PROPERTY, DAMAGED_CROPS, BEGIN_LAT, BEGIN_LON, END_LAT, END_LON FROM noaa.`stormdata` WHERE STATE_FIPS= '93';
-- CREATE TABLE noaa.`LAKE ONTARIO DATA` AS SELECT EPISODE_ID, EVENT_ID, BEGIN_YEARMONTH, END_YEARMONTH, STATE, STATE_FIPS, EVENT_TYPE, INJURIES_DIRECT, INJURIES_INDIRECT, DEATHS_DIRECT, DEATHS_INDIRECT, DAMAGED_PROPERTY, DAMAGED_CROPS, BEGIN_LAT, BEGIN_LON, END_LAT, END_LON FROM noaa.`stormdata` WHERE STATE_FIPS= '94';
-- CREATE TABLE noaa.`LAKE ERIE DATA` AS SELECT EPISODE_ID, EVENT_ID, BEGIN_YEARMONTH, END_YEARMONTH, STATE, STATE_FIPS, EVENT_TYPE, INJURIES_DIRECT, INJURIES_INDIRECT, DEATHS_DIRECT, DEATHS_INDIRECT, DAMAGED_PROPERTY, DAMAGED_CROPS, BEGIN_LAT, BEGIN_LON, END_LAT, END_LON FROM noaa.`stormdata` WHERE STATE_FIPS= '95';
-- CREATE TABLE noaa.`VIRGIN ISLANDS DATA` AS SELECT EPISODE_ID, EVENT_ID, BEGIN_YEARMONTH, END_YEARMONTH, STATE, STATE_FIPS, EVENT_TYPE, INJURIES_DIRECT, INJURIES_INDIRECT, DEATHS_DIRECT, DEATHS_INDIRECT, DAMAGED_PROPERTY, DAMAGED_CROPS, BEGIN_LAT, BEGIN_LON, END_LAT, END_LON FROM noaa.`stormdata` WHERE STATE_FIPS= '96';
-- CREATE TABLE noaa.`AMERICAN SAMOA DATA` AS SELECT EPISODE_ID, EVENT_ID, BEGIN_YEARMONTH, END_YEARMONTH, STATE, STATE_FIPS, EVENT_TYPE, INJURIES_DIRECT, INJURIES_INDIRECT, DEATHS_DIRECT, DEATHS_INDIRECT, DAMAGED_PROPERTY, DAMAGED_CROPS, BEGIN_LAT, BEGIN_LON, END_LAT, END_LON FROM noaa.`stormdata` WHERE STATE_FIPS= '97';
-- CREATE TABLE noaa.`GUAM DATA` AS SELECT EPISODE_ID, EVENT_ID, BEGIN_YEARMONTH, END_YEARMONTH, STATE, STATE_FIPS, EVENT_TYPE, INJURIES_DIRECT, INJURIES_INDIRECT, DEATHS_DIRECT, DEATHS_INDIRECT, DAMAGED_PROPERTY, DAMAGED_CROPS, BEGIN_LAT, BEGIN_LON, END_LAT, END_LON FROM noaa.`stormdata` WHERE STATE_FIPS= '98';
-- CREATE TABLE noaa.`PUERTO RICO DATA` AS SELECT EPISODE_ID, EVENT_ID, BEGIN_YEARMONTH, END_YEARMONTH, STATE, STATE_FIPS, EVENT_TYPE, INJURIES_DIRECT, INJURIES_INDIRECT, DEATHS_DIRECT, DEATHS_INDIRECT, DAMAGED_PROPERTY, DAMAGED_CROPS, BEGIN_LAT, BEGIN_LON, END_LAT, END_LON FROM noaa.`stormdata` WHERE STATE_FIPS= '99';

SELECT *
FROM `noaa`.`ohio data summary`
WHERE EVENT_ID = 53835;

ALTER TABLE `OHIO DATA SUMMARY`
ADD COLUMN BEGIN_LAT text DEFAULT NULL;
-- ADD COLUMN BEGIN_LON text DEFAULT NULL,
-- ADD COLUMN END_LAT text DEFAULT NULL,
-- ADD COLUMN END_LON text DEFAULT NULL;

-- select * 
-- from `noaa`.`ohio data summary`
-- WHERE EVENT_ID = 5323115;

SELECT EVENT_ID, MIN(odata.EPISODE_ID)
FROM `ohio data` as odata
WHERE odata.EVENT_ID = 1000842
GROUP BY EVENT_ID;

UPDATE `OHIO DATA SUMMARY`
SET
BEGIN_LAT = (
		SELECT BEGIN_LAT
		FROM `OHIO DATA` as odata
		WHERE EPISODE_ID in (
        SELECT *
        FROM(
			SELECT MIN(odata.EPISODE_ID)
			FROM `ohio data` as odata, `ohio data summary` as odatsum
            WHERE odata.EVENT_ID = odatsum.EVENT_ID
			GROUP BY odata.EVENT_ID
			)tblTmp)
        )
WHERE 
	 EVENT_ID in (
		SELECT odata.EVENT_ID
        FROM `OHIO DATA` as odata
        WHERE odata.EVENT_ID = EVENT_ID
        );
-- END_LAT = (
-- 		SELECT END_LAT
-- 		FROM `OHIO DATA`
-- 		GROUP BY EVENT_ID
--         ORDER BY EPISODE_ID desc
--         LIMIT 1
--         ),
-- BEGIN_LON = (
-- 		SELECT BEGIN_LON
-- 		FROM `OHIO DATA`
-- 		GROUP BY EVENT_ID
--         ORDER BY EPISODE_ID asc
-- 		LIMIT 1
--         ),
-- END_LON = (
-- 		SELECT END_LAT
-- 		FROM `OHIO DATA`
-- 		GROUP BY EVENT_ID
-- 		ORDER BY EPISODE_ID desc
-- 		LIMIT 1
--         )
-- WHERE 
-- 	 EVENT_ID in (
-- 		SELECT odata.EVENT_ID
--         FROM `OHIO DATA` as odata
--         WHERE odata.EVENT_ID = EVENT_ID
--         );

-- 
-- END_LAT = (
-- 	SELECT END_LAT
-- 		FROM `noaa`.`OHIO DATA`
-- 		WHERE EPISODE_ID = MAX(EPISODE_ID)
-- 		GROUP BY EVENT_ID
--         ),
-- END_LON = (
-- 	SELECT END_LON
-- 		FROM `noaa`.`OHIO DATA`
-- 		WHERE EPISODE_ID = MAX(EPISODE_ID)
-- 		GROUP BY EVENT_ID
--         )
