ALTER TABLE `OHIO DATA SUMMARY` ADD COLUMN BEGIN_YEARMONTH int DEFAULT NULL, ADD COLUMN END_YEARMONTH int DEFAULT NULL, ADD COLUMN EVENT_TYPE text DEFAULT NULL;

ALTER TABLE `ohio data summary` as odatsum
	SET 

